### PR TITLE
Handle inexistant config file

### PR DESCRIPTION
**Pull request by blogh**

### CODE REVIEW

**Comment by blogh** [comment]
This PR is for #61.

@dlax is there a better way to do this ?

**Comment by dlax** [comment]
Did you try using a `click.File()` argument type? According to its [documentation](https://click.palletsprojects.com/en/8.1.x/arguments/#file-args), click will try to open the file early enough to report I/O errors to the user:
~~~
$ check_patroni --config no-such-file
Usage: check_patroni [OPTIONS] COMMAND [ARGS]...
Try 'check_patroni --help' for help.

Error: Invalid value for '--config': 'no-such-file': No such file or directory
~~~

**Comment by blogh** [comment]
yes but a nagos plugin shoud return a string like "UNKNOWN: click.exceptions.UsageError: Config File not found" and RC 3 in that case.

**Comment by dlax** [comment]
Why 3? This is `ESRCH 3 No such process`. `ENOENT 2 No such file or directory` seems more appropriate.

**Comment by blogh** [comment]
It's the norm they propose in the Nagios Plugins Development Guidelines.

https://nagios-plugins.org/doc/guidelines.html#AEN78

**Comment by dlax** [comment]
I have pushed a better implementation, in branch "fix_configfile_error" on the main repo: https://github.com/dalibo/check_patroni/compare/fix_configfile_error (based on your commit).

The idea is to only handle IO errors in the `configure()` callback, and then possibly exit (with rc 3) from there.

**Comment by dlax** [comment]
WIth the version posted above:
~~~
$ check_patroni --config no-such-file
failed to read configuration: [Errno 2] No such file or directory: 'no-such-file'
$ echo $?
3
$ check_patroni --config /etc/postgresql/16/main/pg_hba.conf 
failed to read configuration: [Errno 13] Permission denied: '/etc/postgresql/16/main/pg_hba.conf'
$ echo $?
3
~~~

**Comment by blogh** [comment]
ha yes, mutch better. Th. I'll use that one instead.

**Pull request closed without merging**
